main:
  - name: About
    url: "/#about"
    weight: 10

  - name: Projects
    url: "/#projects"
    weight: 20

  - name: Resume
    pageRef: /resume
    weight: 30


# footer social link
social:
  - name: GitHub
    url: https://github.com/CyborgKendoka
    weight: 10
    params:
      icon: github
  - name: Itch
    url: https://aomame.itch.io/
    weight: 20
    params:
      icon: itch
  - name: LinkedIn
    url: https://www.linkedin.com/in/sontje-mrosla-6a333037b/
    weight: 30
    params:
      icon: linkedin
  - name: Email
    url: mailto:mrosla.sontje@gmail.com
    weight: 40
    params:
      icon: email
